image: quantumtinkerer/research

stages:
  - test
  - asv-setup
  - benchmark
  - deploy

test:
  stage: test
  script:
     - py.test adaptive
  allow_failure: true

setup asv:
  stage: asv-setup
  script:
    - pip install https://github.com/airspeed-velocity/asv/archive/master.zip  # we need github.com/airspeed-velocity/asv/pull/540 which is not in the latest release
    - asv machine --config=benchmarks/asv.conf.json --yes

benchmarks for master:
  stage: benchmark
  script:
    - asv run --config=benchmarks/asv.conf.json --yes --skip-existing-commits ALL 
  artifacts:
    paths:
      - benchmarks/results
      - benchmarks/env
    expire_in: 7d

benchmarks not master:
  stage: benchmark
  script:
    - asv run --config=benchmarks/asv.conf.json ${CI_COMMIT_REF_NAME}{u}..master
  except:
    - master

upload_benchmarks:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh && ssh-keyscan tnw-tn1.tudelft.net >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  script:
    - asv publish
    - "rsync -ravz --delete benchmarks/html/* adaptive-asv@tnw-tn1.tudelft.net:"
  after_script:
    - rm -rf ~/.ssh
